Settings:
  onjoin:
    teleport: true
    clearInventory: false
    clearXP: false
    clearPotionEffects: false
  external-economy: false
  
#Storage
# current possibilities: sqlite, mysql, h2 or mongodb
storage-method: h2

data:
# Uses standard DB engine port by default
# MySQL: 3306, PostgreSQL: 5432, MongoDB: 27017
# Specify as "host:port" if differs
  address: localhost
  database: playerhunt
  username: root
  password: ''
  pool-size: 10 # The size of the MySQL connection pool.
  
# The prefix for all PlayerHunter tables. Change this is you want to use different tables for
# different servers.
#
  table_prefix: 'playerhunter_'

# The prefix to use for all LuckPerms collections. Change this if you want to use different
# collections for different servers. The default is no prefix.
  mongodb_collection_prefix: ''
  
# This controls how fast you want Playerhunter to fetch and save data to the DB
# to disable this set it to -1
  sync-minutes: -1

lobby: